# Generated by Django 4.1.4 on 2023-03-21 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.URLField(blank=True, max_length=2000, null=True)),
                ('courseCode', models.CharField(max_length=10, unique=True)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ENG', 'English'), ('HIN', 'Hindi')], default='ENG', max_length=5)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
                ('studentsInParticularLanguage', models.ManyToManyField(blank=True, related_name='students_in_a_language', to='Profile.student')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_topics', to='Content_app.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subjectCode', models.CharField(max_length=10, unique=True)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subjects', to='Content_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(blank=True, null=True)),
                ('quesImg', models.URLField(blank=True, max_length=2000, null=True)),
                ('marks', models.FloatField(default=4)),
                ('quesTime', models.DurationField(default=datetime.timedelta(seconds=30))),
                ('difficultyLevel', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=8)),
                ('answerExplanation', models.TextField(blank=True, null=True)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_questions', to='Content_app.chapter')),
                ('quesLanguage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_of_questions', to='Content_app.language')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_questions', to='Content_app.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_questions', to='Content_app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionText', models.CharField(blank=True, max_length=255, null=True)),
                ('optionImg', models.URLField(blank=True, max_length=2000, null=True)),
                ('isCorrect', models.BooleanField(default=False)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='Content_app.question')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='courseLanguage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_Language', to='Content_app.language'),
        ),
        migrations.AddField(
            model_name='course',
            name='institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institute_courses', to='Profile.institute'),
        ),
        migrations.AddField(
            model_name='course',
            name='studentsInCourse',
            field=models.ManyToManyField(blank=True, related_name='students_in_course', to='Profile.student'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_chapters', to='Content_app.subject'),
        ),
    ]
