# Generated by Django 4.1.4 on 2023-03-21 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceToken', models.TextField(blank=True, max_length=2000, null=True)),
                ('avatar', models.CharField(blank=True, max_length=2, null=True)),
                ('name', models.CharField(max_length=255)),
                ('emailID', models.EmailField(max_length=254, unique=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('residentialState', models.CharField(max_length=30)),
                ('competitiveExamSelection', models.CharField(choices=[('JEE', 'JEE'), ('GATE', 'GATE'), ('NEET', 'NEET'), ('CAT', 'CAT'), ('GMAT', 'GMAT'), ('UPSC', 'UPSC'), ('SSC', 'SSC')], max_length=7)),
                ('studentInstituteType', models.CharField(choices=[('Inst', 'Institute'), ('Sch', 'School'), ('Clg', 'College'), ('Univ', 'University')], max_length=5)),
                ('isLogin', models.BooleanField(default=False)),
                ('joiningTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('studentUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSessionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginTimestamp', models.DateTimeField(blank=True, null=True)),
                ('logoutTimestamp', models.DateTimeField(blank=True, null=True)),
                ('timeSpend', models.DurationField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.student')),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serverKey', models.TextField(blank=True, max_length=2000, null=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.URLField(blank=True, max_length=1500, null=True)),
                ('instituteCode', models.CharField(blank=True, max_length=20, null=True)),
                ('emailID', models.EmailField(blank=True, max_length=254, null=True)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('aboutUs', models.URLField(blank=True, max_length=2000, null=True)),
                ('typeOfInstitute', models.CharField(choices=[('Inst', 'Institute'), ('Sch', 'School'), ('Clg', 'College'), ('Univ', 'University')], default='Inst', max_length=5)),
                ('levelOfInstitute', models.CharField(choices=[('T1', 'Tier - I'), ('T2', 'Tier - II'), ('T3', 'Tier - III')], default='T1', max_length=3)),
                ('badge', models.CharField(choices=[('B', 'Bronze'), ('S', 'Silver'), ('G', 'Gold'), ('D', 'Diamond')], default='B', max_length=2)),
                ('fullAddress', models.TextField(blank=True, null=True)),
                ('websiteURL', models.URLField(blank=True, null=True)),
                ('facebookURL', models.URLField(blank=True, null=True)),
                ('instagramURL', models.URLField(blank=True, null=True)),
                ('twitterURL', models.URLField(blank=True, null=True)),
                ('linkedinURL', models.URLField(blank=True, null=True)),
                ('telegramURL', models.URLField(blank=True, null=True)),
                ('whatsappToSendDoubt', models.BooleanField(default=False)),
                ('whatsappURL', models.URLField(blank=True, null=True)),
                ('showCourses', models.BooleanField(default=False)),
                ('joiningTimestamp', models.DateTimeField(auto_now_add=True)),
                ('instituteUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
