# Generated by Django 4.1.4 on 2023-03-21 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Content_app', '0001_initial'),
        ('Profile', '0001_initial'),
        ('Play_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAttempted', models.BooleanField(default=False)),
                ('attemptDuration', models.DurationField(blank=True, null=True)),
                ('attemptedTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_attempted_questions', to='Content_app.chapter')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_attempted_questions', to='Content_app.course')),
                ('optionAttempted', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attempted_option', to='Content_app.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempted_questions', to='Content_app.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attempted_questions', to='Profile.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_attempted_questions', to='Content_app.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_attempted_questions', to='Content_app.topic')),
            ],
            options={
                'verbose_name': 'Attempted Question',
            },
        ),
        migrations.CreateModel(
            name='DuosChallengeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCompleted', models.BooleanField(default=False)),
                ('marksScoredForCA', models.FloatField(default=0)),
                ('marksDeductedForWA', models.FloatField(default=0)),
                ('finalMarksScored', models.FloatField(default=0)),
                ('nca', models.IntegerField(default=0)),
                ('nwa', models.IntegerField(default=0)),
                ('nqs', models.IntegerField(default=0)),
                ('dcAttemptDuration', models.DurationField(blank=True, null=True)),
                ('rewardWon', models.CharField(blank=True, max_length=100, null=True)),
                ('isViewedRewardPopout', models.BooleanField(default=False)),
                ('submittedTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
                ('attemptedQuestions', models.ManyToManyField(blank=True, related_name='dc_attempted_questions', to='Challenge_Analytics_app.attemptedquestion')),
                ('dc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='particular_dc_results', to='Play_app.duoschallenge')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_duos_challenge_results', to='Profile.student')),
            ],
            options={
                'verbose_name': 'Duos Challenge Result',
            },
        ),
    ]
