# Generated by Django 4.1.4 on 2023-03-21 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PruvaAIAppFunctionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPruvaAIAppActive', models.BooleanField(default=True)),
                ('isCCFActive', models.BooleanField(default=True)),
                ('isGFDCFActive', models.BooleanField(default=True)),
                ('isGRGCFActive', models.BooleanField(default=True)),
                ('isWMRFActive', models.BooleanField(default=True)),
                ('isRFActive', models.BooleanField(default=True)),
                ('minWithdrawAmt', models.IntegerField(default=0)),
                ('minDuosChallengesForWithdraw', models.IntegerField(default=0)),
                ('minEntryAmt', models.IntegerField(default=10)),
                ('eachTWCoinValue', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'PruvaAI App Functionality',
                'verbose_name_plural': 'PruvaAI App Functionalities',
            },
        ),
    ]
