# Generated by Django 4.1.4 on 2023-03-21 02:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Content_app', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DuosChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('entryAmt', models.IntegerField(default=0)),
                ('winningAmt', models.IntegerField(default=0)),
                ('totalMarks', models.FloatField(default=40)),
                ('correctAnswerMarks', models.FloatField(default=4)),
                ('negativeMarks', models.FloatField(default=1)),
                ('challengeTime', models.DurationField(default=datetime.timedelta(seconds=300))),
                ('activeTimestamp', models.DateTimeField(blank=True, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('isPublish', models.BooleanField(default=False)),
                ('isThisFreeChallenge', models.BooleanField(default=False)),
                ('isAttemptedByChallenger', models.BooleanField(default=False)),
                ('isAcceptedByCompetitor', models.BooleanField(default=False)),
                ('completedTimestamp', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('createdTimestamp', models.DateTimeField(auto_now_add=True)),
                ('updatedTimestamp', models.DateTimeField(auto_now=True)),
                ('challengeLanguage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='language_of_duos_challenges', to='Content_app.language')),
                ('challenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_creating_duos_challenges', to='Profile.student')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duos_challenge_chapters', to='Content_app.chapter')),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_accepting_duos_challenges', to='Profile.student')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duos_challenge_courses', to='Content_app.course')),
                ('quesInChallenge', models.ManyToManyField(blank=True, related_name='questions_in_duos_challenge', to='Content_app.question')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duos_challenge_subjects', to='Content_app.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duos_challenge_topics', to='Content_app.topic')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duos_challenge_winners', to='Profile.student')),
            ],
        ),
    ]
