# Generated by Django 4.1.4 on 2023-03-21 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPAICoinsWalletTransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinsTransacted', models.IntegerField(default=0)),
                ('PAIcTransactionStatus', models.CharField(choices=[('CR', 'Credited'), ('DR', 'Debited')], default='DR', max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_doing_tw_coins_transactions', to='Profile.student')),
            ],
        ),
        migrations.CreateModel(
            name='PruvaAICoinsWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pruvaAICoin', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.student')),
            ],
        ),
    ]
